#!/usr/bin/env node
/**
 * h173k Wallet - build output checks.
 *
 * Run after `npm run build`. These catch the class of mistake where source code
 * looks correct but never reaches users: the service worker is generated by
 * workbox, so hand-written worker code only runs if it is imported into the
 * generated bundle. A fix once sat in public/sw.js — overwritten at build time,
 * so it worked in `vite dev` and did nothing in production, with no error
 * anywhere to reveal it.
 *
 * Reading the source cannot detect that. Reading dist/ can.
 */

import fs from 'node:fs'
import path from 'node:path'

const DIST = 'dist'
const failures = []
const notes = []

function read(rel) {
  const p = path.join(DIST, rel)
  return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null
}

function check(name, condition, detail) {
  if (condition) {
    console.log('  ok   ' + name)
  } else {
    console.log('  FAIL ' + name + (detail ? ' -> ' + detail : ''))
    failures.push(name)
  }
}

console.log('\nBuild output checks\n')

// ---- the build actually happened ----
const swGenerated = read('sw.js')
if (!swGenerated) {
  console.error('dist/sw.js missing — run `npm run build` first.')
  process.exit(1)
}

// ---- custom worker code is imported into the generated worker ----
check(
  'generated worker imports our handlers',
  swGenerated.includes('sw-notifications.js'),
  'workbox.importScripts in vite.config.js no longer points at it'
)

const swCustom = read('sw-notifications.js')
check('custom worker file is emitted', !!swCustom)

if (swCustom) {
  check(
    'notification clicks are handled',
    swCustom.includes('notificationclick'),
    'clicking a notification would do nothing'
  )
  check(
    'clicks tell the app which chat to open',
    swCustom.includes('h173k-open-chat'),
    'group and thread notifications would focus the window but open nothing'
  )
}

// ---- exactly one worker registration path ----
const indexHtml = read('index.html') || ''
check(
  'VitePWA registers the worker',
  indexHtml.includes('registerSW.js'),
  'no registration script injected'
)
check(
  'no second, hand-rolled registration',
  !/navigator\.serviceWorker\.register\(\s*['"]\/sw\.js/.test(indexHtml),
  'two registrations race each other and hide which worker is live'
)

// ---- a stray public/sw.js would be silently overwritten ----
if (fs.existsSync('public/sw.js')) {
  failures.push('public/sw.js exists')
  console.log(
    '  FAIL public/sw.js exists -> it is overwritten by the generated worker, ' +
    'so anything in it runs in dev only. Put worker code in public/sw-notifications.js.'
  )
} else {
  console.log('  ok   no shadowed public/sw.js')
}

// ---- product name in user-visible metadata ----
const manifest = read('manifest.webmanifest')
if (manifest) {
  check(
    'manifest uses the lowercase product name',
    !/H173[Kk]/.test(manifest),
    'shown under the home-screen icon'
  )
}
check(
  'page title uses the lowercase product name',
  !/<title>[^<]*H173[Kk]/.test(indexHtml)
)

// ---- version reaches the bundle the user runs ----
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))
const bundles = fs
  .readdirSync(path.join(DIST, 'assets'))
  .filter((f) => f.endsWith('.js'))
  .map((f) => read(path.join('assets', f)))
  .join('')
check(
  `version ${pkg.version} is in the shipped bundle`,
  bundles.includes(pkg.version),
  'the About screen would show a stale version'
)

const lock = JSON.parse(fs.readFileSync('package-lock.json', 'utf8'))
check(
  'package-lock version matches package.json',
  lock.version === pkg.version,
  `${lock.version} vs ${pkg.version} — npm ci would complain`
)

console.log()
if (failures.length) {
  console.error(`${failures.length} check(s) FAILED\n`)
  process.exit(1)
}
console.log('All build output checks passed\n')
if (notes.length) notes.forEach((n) => console.log('  note: ' + n))
